import { useState } from 'react';
import { NextPage } from 'next';
import Head from 'next/head'
import { RandomFox } from '@/components/RandomFox'


// Generates a random number between 1 and 122
const random = () => Math.floor(Math.random() * 122) + 1;

const generateId = () => Math.random().toString(36).substring(2, 9);

type ImageItem = { id: string; url: string }

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<ImageItem>>([]);

  const addNewFox = () => {
    const newImageItem = {
      id:generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`
    };
    setImages([...images,newImageItem]);
  };


  return (
    <div>
      <Head>
        <title>React-Typescript</title>
        <meta name="description" content="Generated by platzi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline"> Hello Curly! </h1>
        <button onClick={addNewFox}>Add New Fox</button>
        {images.map(({id, url}) => (
          <div key={id} className='p-4'>
            <RandomFox image={url} />
          </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
