import { RandomFox } from '@/components/RandomFox'
import Head from 'next/head'

// Generates a random number between 1 and 122
const randomNumber = () => Math.floor(Math.random() * 122) + 1;

export default function Home() {
  return (
    <div>
      <Head>
        <title>React-Typescript</title>
        <meta name="description" content="Generated by platzi" />
               <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className="text-3xl font-bold underline">
      Hello Curly!
    </h1>
    <RandomFox image= {`https://randomfox.ca/images/${randomNumber()}.jpg`}/>
      </main>
      <footer></footer>
    </div>
  )
}
