import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>React-Typescript</title>
        <meta name="description" content="Generated by platzi" />
               <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className="text-3xl font-bold underline">
      Hello Curly!
    </h1>
      </main>
      <footer></footer>
    </>
  )
}
